import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '# GENERATED BY livery. Do not edit by hand.\n'
    '# Regenerate with `dart run livery`.\n'
    '\n';

/// A project holding [manifest] and every file in [files], keyed by its path
/// relative to the project root.
TestProject _project(String manifest, {Map<String, String> files = const <String, String>{}}) {
  final project = TestProject.create()..writeManifest(manifest);
  for (final MapEntry(:key, :value) in files.entries) {
    project.write(key, value);
  }

  return project;
}

/// Runs [project] with [args] and returns the body of `out.properties` after
/// the header.
String _render(TestProject project, {List<String> args = const <String>[]}) {
  final result = project.run(args);
  expect(result.exitCode, 0, reason: '$result');

  return project.read('out.properties')!.substring(_header.length);
}

/// Runs [project] with [args], expects exit code 1 and no `out.properties`,
/// and returns stderr.
String _fail(TestProject project, {List<String> args = const <String>[]}) {
  final result = project.run(args);

  expect(result.exitCode, 1, reason: '$result');
  expect(result.err, isNot(contains('#0')), reason: 'no stack trace');
  expect(project.exists('out.properties'), isFalse, reason: 'nothing written');

  return result.err;
}

/// A two-app manifest whose apps `demo` and `kiosk` live in the files the
/// `apps` registry names, with the app define [appDefine].
String _appsManifest({String appDefine = 'APP: {values: [demo, kiosk], default: demo}', String extra = ''}) => '''
version: 1
defines:
  $appDefine
$extra
apps:
  demo: config/demo.yaml
  kiosk: config/kiosk.yaml
outputs:
  android: {files: [out.properties]}
''';

const _demo = '''
config:
  android: {name: Demo, port: 80}
''';

const _kiosk = '''
config:
  android: {name: Kiosk, port: 8080}
''';

void main() {
  group('config_file', () {
    test('loads the config and its overrides from the file, relative to the manifest', () {
      final project =
          TestProject.create()
            ..write('tools/livery.yaml', '''
version: 1
root: ..
defines:
  ENV: {values: [dev, production], default: dev}
config_file: config/app.yaml
outputs:
  android: {files: [out.properties]}
''')
            ..write('tools/config/app.yaml', '''
config:
  android: {url: dev.example.com}
overrides:
  - when: {ENV: production}
    set:
      android: {url: example.com}
''');

      expect(_render(project, args: <String>['-c', 'tools/livery.yaml', '-D', 'ENV=production']), 'url=example.com\n');
    });

    test('a config file accepts only config and overrides', () {
      final project = _project(
        'version: 1\nconfig_file: app.yaml\noutputs:\n  android: {files: [out.properties]}\n',
        files: <String, String>{'app.yaml': 'config:\n  android: {a: b}\noutputs: {}\n'},
      );

      expect(
        _fail(project),
        contains('${project.path('app.yaml')}: [outputs] unknown key `outputs`, accepted keys are config, overrides'),
      );
    });

    test('override checks report the config file', () {
      final project = _project(
        'version: 1\nconfig_file: app.yaml\noutputs:\n  android: {files: [out.properties]}\n',
        files: <String, String>{'app.yaml': 'config:\n  android: {a: b}\noverrides:\n  - set: {android: {c: d}}\n'},
      );

      expect(_fail(project), contains('${project.path('app.yaml')}: [overrides]'));
    });

    for (final (name, content) in <(String, String)>[('an empty', ''), ('a comment-only', '# nothing yet\n')]) {
      test('$name config file fails', () {
        final project = _project(
          'version: 1\nconfig_file: app.yaml\noutputs:\n  android: {files: [out.properties]}\n',
          files: <String, String>{'app.yaml': content},
        );

        expect(
          _fail(project),
          contains('${project.path('app.yaml')}: [<root>] the config file is empty; expected `config` and `overrides`'),
        );
      });
    }

    test('a missing config file fails, naming it', () {
      final project = _project('version: 1\nconfig_file: app.yaml\noutputs:\n  android: {files: [out.properties]}\n');

      expect(_fail(project), contains('[config_file] cannot read `app.yaml`'));
    });
  });

  group('config sources', () {
    for (final (first, second) in <(String, String)>[
      ('config: {android: {a: b}}', 'config_file: app.yaml'),
      ('overrides: []', 'config_file: app.yaml'),
      ('config: {android: {a: b}}', 'apps: {demo: demo.yaml}'),
      ('config_file: app.yaml', 'app_pattern: "{APP}.yaml"'),
      ('apps: {demo: demo.yaml}', 'app_pattern: "{APP}.yaml"'),
    ]) {
      final firstKey = first.split(':').first;
      final secondKey = second.split(':').first;
      test('$firstKey and $secondKey are mutually exclusive', () {
        final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
$first
$second
outputs:
  android: {files: [out.properties]}
''');

        expect(_fail(project), contains('[$secondKey] `$firstKey` and `$secondKey` are mutually exclusive'));
      });
    }

    test('config and overrides together are one source', () {
      final project = _project('''
version: 1
config: {android: {a: b}}
overrides: [{set: {android: {a: c}}}]
outputs:
  android: {files: [out.properties]}
''');

      expect(_render(project), 'a=c\n');
    });

    test('app_define without apps or app_pattern fails', () {
      final project = _project('''
version: 1
app_define: APP
config: {android: {a: b}}
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('[app_define] `app_define` only applies with `apps` or `app_pattern`'));
    });
  });

  group('apps', () {
    test('the app define selects the app config', () {
      final files = <String, String>{'config/demo.yaml': _demo, 'config/kiosk.yaml': _kiosk};

      expect(_render(_project(_appsManifest(), files: files)), 'name=Demo\nport=80\n');
      expect(
        _render(_project(_appsManifest(), files: files), args: <String>['-D', 'APP=kiosk']),
        'name=Kiosk\nport=8080\n',
      );
    });

    test('app_define names another define', () {
      final project = _project(
        _appsManifest(appDefine: 'BRAND: {values: [demo, kiosk], required: true}', extra: 'app_define: BRAND'),
        files: <String, String>{'config/demo.yaml': _demo, 'config/kiosk.yaml': _kiosk},
      );

      expect(_render(project, args: <String>['-D', 'BRAND=kiosk']), 'name=Kiosk\nport=8080\n');
    });

    test('the app is matched exactly', () {
      final project = _project(
        _appsManifest(),
        files: <String, String>{'config/demo.yaml': _demo, 'config/kiosk.yaml': _kiosk},
      );

      expect(
        _fail(project, args: <String>['-D', 'APP=Kiosk']),
        contains('define `APP` has invalid value `Kiosk`, expected one of demo, kiosk'),
      );
    });

    test('an undeclared app define fails', () {
      final project = _project(_appsManifest(appDefine: 'ENV: [dev]'));

      expect(_fail(project), contains('[apps] the app define `APP` is not a declared define'));
    });

    test('an undeclared app_define fails at app_define', () {
      final project = _project(_appsManifest(extra: 'app_define: BRAND'));

      expect(_fail(project), contains('[app_define] the app define `BRAND` is not a declared define'));
    });

    test('a free-form app define fails', () {
      final project = _project(_appsManifest(appDefine: 'APP: {default: demo}'));

      expect(_fail(project), contains('[defines.APP] `APP` selects the app, so it must declare `values`'));
    });

    test('an app define with no values fails', () {
      final project = _project(_appsManifest(appDefine: 'APP: {values: [], required: true}'));

      expect(_fail(project), contains('[defines.APP] `APP` selects the app, so it must declare `values`'));
    });

    test('an app define that can stay unresolved fails', () {
      final project = _project(_appsManifest(appDefine: 'APP: [demo, kiosk]'));

      expect(
        _fail(project),
        contains('[defines.APP] `APP` selects the app, so it must be `required` or have a `default`'),
      );
    });

    test('the registry keys must equal the app define values', () {
      final project = _project(_appsManifest(appDefine: 'APP: {values: [demo, tv], default: demo}'));

      expect(
        _fail(project),
        contains('[apps] the apps must be the values of `APP`, demo, tv: `tv` has no entry, `kiosk` is not a value'),
      );
    });

    test('a registry entry must be a string', () {
      final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
apps:
  demo: [a.yaml]
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('[apps.demo] expected a string, got a list'));
    });

    test('a broken app file fails while another app is built', () {
      final project = _project(
        _appsManifest(),
        files: <String, String>{
          'config/demo.yaml': _demo,
          'config/kiosk.yaml': '$_kiosk\noverrides:\n  - set: {android: {nmae: Kiosk TV}}\n',
        },
      );

      expect(_fail(project), contains('${project.path('config/kiosk.yaml')}: [overrides]'));
    });

    test('an empty app file fails while another app is built', () {
      final project = _project(
        _appsManifest(),
        files: <String, String>{'config/demo.yaml': _demo, 'config/kiosk.yaml': ''},
      );

      expect(_fail(project), contains('${project.path('config/kiosk.yaml')}: [<root>] the config file is empty'));
    });

    test('a missing app file fails while another app is built', () {
      final project = _project(_appsManifest(), files: <String, String>{'config/demo.yaml': _demo});

      expect(_fail(project), contains('[apps.kiosk] cannot read `config/kiosk.yaml`'));
    });

    test('every app must have the keys and value types of the first', () {
      final project = _project(
        '''
version: 1
defines:
  APP: {values: [demo, kiosk, tv], default: demo}
apps:
  demo: demo.yaml
  kiosk: kiosk.yaml
  tv: tv.yaml
outputs:
  android: {files: [out.properties]}
''',
        files: <String, String>{
          'demo.yaml': 'config:\n  android: {name: Demo, port: 80, api: {url: a, timeout: 1.5}}\n',
          'kiosk.yaml': 'config:\n  android: {name: Kiosk, port: "80", api: {timeout: 2}, ads: true}\n',
          'tv.yaml': 'config:\n  android: {name: TV, port: 80, api: {url: a, timeout: 1.5}}\n  ios: {}\n',
        },
      );

      expect(
        _fail(project),
        contains(
          '[apps] every app must have the keys and value types of `demo`:\n'
          '  kiosk (kiosk.yaml):\n'
          '    missing `android.api.url`\n'
          '    extra `android.ads`\n'
          '    `android.port` is an int in `demo`, a string here\n'
          '    `android.api.timeout` is a double in `demo`, an int here\n'
          '  tv (tv.yaml):\n'
          '    extra `ios`\n',
        ),
      );
    });
  });

  group('app_pattern', () {
    test('substitutes the app and the other defines', () {
      final project = _project(
        '''
version: 1
defines:
  APP: {values: [demo, kiosk], default: demo}
  ENV: {values: [dev, production], default: dev}
app_pattern: "config/{ENV}/{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''',
        files: <String, String>{
          'config/dev/demo.yaml': _demo,
          'config/dev/kiosk.yaml': _kiosk,
          'config/production/demo.yaml': 'config:\n  android: {name: Demo Prod, port: 443}\n',
          'config/production/kiosk.yaml': 'config:\n  android: {name: Kiosk Prod, port: 443}\n',
        },
      );

      expect(_render(project, args: <String>['-D', 'APP=kiosk']), 'name=Kiosk\nport=8080\n');
      expect(_render(project, args: <String>['-D', 'ENV=production']), 'name=Demo Prod\nport=443\n');
    });

    test('loads every app the app define lists', () {
      final project = _project(
        '''
version: 1
defines:
  APP: {values: [demo, kiosk], default: demo}
app_pattern: "{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''',
        files: <String, String>{'demo.yaml': _demo},
      );

      expect(_fail(project), contains('[app_pattern] cannot read `kiosk.yaml`'));
    });

    test('a placeholder naming an undeclared define fails', () {
      final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
app_pattern: "{env}/{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('[app_pattern] `{env}` is not a declared define; declared defines are APP'));
    });

    test('a pattern without the app placeholder fails', () {
      final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
app_pattern: "app.yaml"
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('[app_pattern] the pattern must contain `{APP}`, the app define'));
    });

    test('a placeholder of an unresolved define fails', () {
      final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
  ENV:
app_pattern: "{ENV}/{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('[app_pattern] `{ENV}` has no value: define `ENV` is unresolved'));
    });

    for (final value in <String>['a/b', r'a\b', '..', 'a..b']) {
      test('a substituted value holding `$value` fails', () {
        final project = _project('''
version: 1
defines:
  APP: {values: [demo], default: demo}
  ENV:
app_pattern: "{ENV}/{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''');

        expect(
          _fail(project, args: <String>['-D', 'ENV=$value']),
          contains('[app_pattern] `{ENV}` would be `$value`; a substituted value must not contain `/`, `\\` or `..`'),
        );
      });
    }

    test('an app value holding a path separator fails', () {
      final project = _project('''
version: 1
defines:
  APP: {values: [demo, ../secrets], default: demo}
app_pattern: "{APP}.yaml"
outputs:
  android: {files: [out.properties]}
''');

      expect(_fail(project), contains('`{APP}` would be `../secrets`'));
    });
  });

  group('defines only', () {
    test('a manifest without config is valid when no output merges a section', () {
      final project = _project('''
version: 1
defines:
  ENV: {values: [dev], default: dev}
outputs:
  android:
    merge: []
    include_defines: true
    files: [out.properties]
''');

      expect(_render(project), 'ENV=dev\n');
    });

    test('merging a section still fails without config', () {
      final project = _project('version: 1\noutputs:\n  android: {files: [out.properties]}\n');

      expect(_fail(project), contains('merges section `android`, which the config does not define'));
    });
  });
}
