import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '// dart format off\n'
    '// GENERATED BY livery. Do not edit by hand.\n'
    '// Regenerate with `dart run livery`.\n'
    '// ignore_for_file: type=lint\n'
    '\n';

/// Runs a manifest with [defines] and [config] whose single `dart` output
/// `app` has the extra keys [output] and writes `lib/app_config.g.dart`.
(TestProject, CliResult) _run({
  String defines = '',
  String config = '',
  String output = '',
  List<String> args = const <String>[],
}) {
  final project =
      TestProject.create()..writeManifest('''
version: 1
$defines
$config
outputs:
  app:
    format: dart
    files: [lib/app_config.g.dart]
$output
''');

  return (project, project.run(args));
}

/// The file [_run] writes after the header, expecting the run to succeed.
String _body({String defines = '', String config = '', String output = '', List<String> args = const <String>[]}) {
  final (project, result) = _run(defines: defines, config: config, output: output, args: args);
  expect(result.exitCode, 0, reason: '$result');
  final contents = project.read('lib/app_config.g.dart')!;
  expect(contents, startsWith(_header));

  return contents.substring(_header.length);
}

/// The error output of [_run], expecting the run to fail without writing.
String _fail({String defines = '', String config = '', String output = ''}) {
  final (project, result) = _run(defines: defines, config: config, output: output);
  expect(result.exitCode, 1, reason: '$result');
  expect(project.exists('lib/app_config.g.dart'), isFalse);

  return result.err;
}

void main() {
  group('enums', () {
    test('a constrained define becomes an enum read from the compile-time environment', () {
      expect(
        _body(
          defines: '''
defines:
  ENV: {values: [dev, production], default: dev}
''',
        ),
        r'''
/// `--dart-define=ENV=<dev|production>`
enum EnvDefine {
  dev('dev'),
  production('production');

  const EnvDefine(this.value);

  /// The value as spelled in the manifest.
  final String value;

  /// Raw `ENV` the running app was compiled with.
  static const String rawValue = String.fromEnvironment('ENV', defaultValue: 'dev');

  /// [rawValue] resolved to a value, `null` when it matches none.
  ///
  /// Const, so branches on it are resolved at compile time and the
  /// unreachable ones are tree-shaken away.
  static const EnvDefine? maybeCurrent =
      rawValue == 'dev' ? dev :
      rawValue == 'production' ? production :
      null;

  /// How the app was launched.
  ///
  /// Throws when `ENV` holds an undeclared value.
  static EnvDefine get current =>
      maybeCurrent ?? (throw StateError('ENV=$rawValue is not one of dev, production'));

  /// [value] resolved to a value, `null` when it matches none.
  ///
  /// Matches exactly, as `String.fromEnvironment` does.
  static EnvDefine? tryParse(String? value) {
    for (final candidate in values) {
      if (candidate.value == value) {
        return candidate;
      }
    }

    return null;
  }
}
''',
      );
    });

    test('a define without a default reads the environment without one', () {
      expect(
        _body(defines: 'defines:\n  FLAVOR: [free, paid]'),
        contains("static const String rawValue = String.fromEnvironment('FLAVOR');\n"),
      );
    });

    test('is named by dart_class when the define sets it', () {
      final body = _body(defines: 'defines:\n  ENV: {values: [dev], dart_class: Environment}');

      expect(body, contains('enum Environment {\n'));
      expect(body, contains('static Environment get current =>'));
    });

    test('is named by the define name in UpperCamel plus Define', () {
      expect(_body(defines: 'defines:\n  BUILD_MODE: [debug]'), contains('enum BuildModeDefine {\n'));
    });

    test('a define name starting with a digit gets a `V` prefix', () {
      expect(_body(defines: 'defines:\n  2FA: [on]'), contains('enum V2faDefine {\n'));
    });

    for (final name in <String>['my class', '1st', 'void']) {
      test('a dart_class `$name` that is not a Dart identifier fails', () {
        expect(
          _fail(defines: 'defines:\n  ENV: {values: [dev], dart_class: "$name"}'),
          contains('[outputs.app] define `ENV` sets `dart_class` to `$name`, which is not a valid Dart identifier'),
        );
      });
    }

    test('values become lowerCamel members', () {
      expect(
        _body(defines: 'defines:\n  MODE: [app-store, PLAY_STORE]'),
        contains("  appStore('app-store'),\n  playStore('PLAY_STORE');\n"),
      );
    });

    test(r'values that are keywords or members every enum has are escaped with `$`', () {
      expect(
        _body(defines: 'defines:\n  MODE: [default, values, index, value, current, maybeCurrent, rawValue, tryParse]'),
        contains(
          "  default\$('default'),\n"
          "  values\$('values'),\n"
          "  index\$('index'),\n"
          "  value\$('value'),\n"
          "  current\$('current'),\n"
          "  maybeCurrent\$('maybeCurrent'),\n"
          "  rawValue\$('rawValue'),\n"
          "  tryParse\$('tryParse');\n",
        ),
      );
    });

    test('a value with a leading digit gets a `v` prefix and one with no letters is `empty`', () {
      expect(_body(defines: 'defines:\n  MODE: ["1x", "-"]'), contains("  v1x('1x'),\n  empty('-');\n"));
    });

    test('a value named like the enum is escaped', () {
      expect(_body(defines: 'defines:\n  MODE: {values: [mode], dart_class: mode}'), contains("  mode\$('mode');\n"));
    });

    test('values and names are written as escaped string literals', () {
      final body = _body(defines: 'defines:\n  MODE: ["it\'s", "\$x", "a\\\\b"]');

      expect(body, contains(r"  itS('it\'s'),"));
      expect(body, contains(r"  x('\$x'),"));
      expect(body, contains(r"  aB('a\\b');"));
      expect(body, contains(r"""StateError('MODE=$rawValue is not one of it\'s, \$x, a\\b')"""));
    });

    test('two values that become one member fail, naming both', () {
      expect(
        _fail(defines: 'defines:\n  MODE: [a-b, a_b]'),
        contains('[outputs.app] define `MODE` values `a-b` and `a_b` both become the Dart enum value `aB`'),
      );
    });

    test('a define that declares no values fails', () {
      expect(
        _fail(defines: 'defines:\n  MODE: []'),
        contains('[outputs.app] define `MODE` declares no values, and a Dart enum needs at least one'),
      );
    });

    test('two defines that become one enum fail, naming both', () {
      expect(
        _fail(defines: 'defines:\n  A_B: [x]\n  a-b: [y]'),
        contains('[outputs.app] defines `A_B` and `a-b` both become the Dart enum `ABDefine`'),
      );
    });

    test('an enum named like the holder class fails, naming both', () {
      expect(
        _fail(
          defines: 'defines:\n  ENV: {values: [dev], dart_class: AppConfig}',
          config: 'config:\n  c: {a: 1}',
          output: '    merge: [c]',
        ),
        contains('[outputs.app] define `ENV` and the holder class both become the Dart class `AppConfig`'),
      );
    });
  });

  group('holder class', () {
    test('holds free-form defines and typed config constants', () {
      expect(
        _body(
          defines: '''
defines:
  BUILD_TAG:
  CHANNEL: {default: beta}
''',
          config: '''
config:
  common:
    app_name: Demo
    api:
      url: https://api.example.com
      timeout: 30
      ratio: 1.5
    debug: false
''',
          output: '    merge: [common]',
        ),
        '''
/// Values resolved by livery.
///
/// Free-form defines are read at compile time; config values are baked in
/// as constants.
abstract final class AppConfig {
  /// `--dart-define=BUILD_TAG=...`
  static const String buildTag = String.fromEnvironment('BUILD_TAG');

  /// `--dart-define=CHANNEL=...`
  static const String channel = String.fromEnvironment('CHANNEL', defaultValue: 'beta');

  static const String appName = 'Demo';
  static const String apiUrl = 'https://api.example.com';
  static const int apiTimeout = 30;
  static const double apiRatio = 1.5;
  static const bool debug = false;
}
''',
      );
    });

    test('is named by class_name when the output sets it', () {
      expect(
        _body(config: 'config:\n  c: {a: 1}', output: '    merge: [c]\n    class_name: Env'),
        contains('abstract final class Env {'),
      );
    });

    for (final name in <String>['my class', '1st', 'class']) {
      test('a class_name `$name` that is not a Dart identifier fails', () {
        expect(
          _fail(output: '    class_name: "$name"'),
          contains('[outputs.app.class_name] `$name` is not a valid Dart identifier'),
        );
      });
    }

    test('is named after the first file when class_name is not set', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  c: {a: 1}
outputs:
  app:
    format: dart
    merge: [c]
    files: [lib/src/remote_config.g.dart, lib/copy.dart]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('lib/copy.dart'), contains('abstract final class RemoteConfig {'));
    });

    test('is LiveryValues when the file name has no letters', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  c: {a: 1}
outputs:
  app:
    format: dart
    merge: [c]
    files: [lib/_.dart]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('lib/_.dart'), contains('abstract final class LiveryValues {'));
    });

    test('is left out when it would hold nothing', () {
      expect(_body(defines: 'defines:\n  ENV: [dev]'), isNot(contains('class')));
    });

    test('doubles keep a decimal point', () {
      expect(
        _body(config: 'config:\n  c: {whole: 2.0, big: 1e21}', output: '    merge: [c]'),
        contains(
          '  static const double whole = 2.0;\n'
          '  static const double big = 1e+21;\n',
        ),
      );
    });

    test('strings are written as escaped literals', () {
      expect(
        _body(
          config: r'''
config:
  c:
    text: "it's $HOME \\ \"q\"\n\r\t\u0001"
''',
          output: '    merge: [c]',
        ),
        contains(r'''  static const String text = 'it\'s \$HOME \\ "q"\n\r\t\x01';'''),
      );
    });

    test('keys that are keywords, Object members or start with a digit are escaped', () {
      expect(
        _body(config: 'config:\n  c: {class: a, hash_code: b, 2fa_enabled: true}', output: '    merge: [c]'),
        contains(
          "  static const String class\$ = 'a';\n"
          "  static const String hashCode\$ = 'b';\n"
          '  static const bool v2faEnabled = true;\n',
        ),
      );
    });

    test('two config keys that become one constant fail, naming both', () {
      expect(
        _fail(config: 'config:\n  c: {api_url: a, api: {url: b}}', output: '    merge: [c]'),
        contains('[outputs.app] config keys `api_url` and `api.url` both become the Dart constant `apiUrl`'),
      );
    });

    test('a free-form define and a config key that become one constant fail, naming both', () {
      expect(
        _fail(defines: 'defines:\n  BUILD_TAG:', config: 'config:\n  c: {build_tag: a}', output: '    merge: [c]'),
        contains(
          '[outputs.app] define `BUILD_TAG` and config key `build_tag` both become the Dart constant `buildTag`',
        ),
      );
    });

    for (final (description, value, message) in <(String, String, String)>[
      ('null', 'null', 'config key `c_key` is null, which a dart output cannot hold'),
      ('a list', '[a, b]', 'config key `c_key` is a list, which a dart output cannot hold'),
      ('NaN', '.nan', 'config key `c_key` is NaN, which a dart output cannot hold'),
      ('infinite', '-.inf', 'config key `c_key` is infinite, which a dart output cannot hold'),
    ]) {
      test('a value that is $description fails, naming the key', () {
        expect(
          _fail(config: 'config:\n  c: {c_key: $value}', output: '    merge: [c]'),
          contains('[outputs.app] $message'),
        );
      });
    }
  });

  group('options', () {
    test('include_defines defaults to on and merge to none', () {
      final body = _body(defines: 'defines:\n  ENV: [dev]\n  TAG:', config: 'config:\n  app: {a: 1}');

      expect(body, contains('enum EnvDefine {'));
      expect(body, contains("String.fromEnvironment('TAG')"));
      expect(body, isNot(contains('static const int a')));
    });

    test('include_defines: false leaves the defines out', () {
      final body = _body(
        defines: 'defines:\n  ENV: [dev]\n  TAG:',
        config: 'config:\n  c: {a: 1}',
        output: '    merge: [c]\n    include_defines: false',
      );

      expect(body, isNot(contains('EnvDefine')));
      expect(body, isNot(contains('fromEnvironment')));
      expect(body, contains('static const int a = 1;'));
    });

    for (final key in <String>['flatten: true', 'separator: "-"', 'page_width: 80']) {
      final name = key.split(':').first;
      test('`$name` is rejected', () {
        expect(
          _fail(output: '    $key'),
          contains(
            '[outputs.app.$name] unknown key `$name`, accepted keys are class_name, files, format, include_defines, merge',
          ),
        );
      });
    }

    for (final format in <String>['properties', 'xcconfig', 'env', 'json']) {
      test('`class_name` is rejected by $format', () {
        final project =
            TestProject.create()..writeManifest('''
version: 1
config:
  out: {a: 1}
outputs:
  out:
    format: $format
    class_name: Config
    files: [out.txt]
''');

        final result = project.run(const <String>[]);

        expect(result.exitCode, 1);
        expect(result.err, contains('[outputs.out.class_name] unknown key `class_name`'));
      });
    }
  });

  group('defines-only output', () {
    test('is identical for every set of define values', () {
      String generate(List<String> args) {
        final project =
            TestProject.create()..writeManifest('''
version: 1
defines:
  ENV: {values: [dev, production], default: dev}
  BUILD_TAG:
outputs:
  app:
    format: dart
    files: [lib/defines.g.dart]
''');
        final result = project.run(args);
        expect(result.exitCode, 0, reason: '$result');

        return project.read('lib/defines.g.dart')!;
      }

      final dev = generate(const <String>[]);

      expect(generate(const <String>['-D', 'ENV=production', '-D', 'BUILD_TAG=nightly']), dev);
    });
  });
}
