import 'dart:convert';

import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '# GENERATED BY livery. Do not edit by hand.\n'
    '# Regenerate with `dart run livery`.\n'
    '\n';

/// A manifest declaring [defines], with one properties output `android` that
/// injects them next to `app_name=Demo`. [extra] goes at the top level.
String _manifest(String defines, {String extra = ''}) => '''
version: 1
$extra
defines:
$defines
config:
  android:
    app_name: Demo
outputs:
  android:
    include_defines: true
    files: [out.properties]
''';

/// One `DART_DEFINES` payload, as the Flutter tool writes it: every
/// `KEY=VALUE` pair base64-encoded, joined by commas.
String _payload(Map<String, String> defines) =>
    <String>[for (final MapEntry(:key, :value) in defines.entries) base64.encode(utf8.encode('$key=$value'))].join(',');

/// Runs [manifest] with [args] and [environment], and returns the written
/// file body after the header.
String _render(String manifest, {List<String> args = const <String>[], Map<String, String> environment = const {}}) {
  final project = TestProject.create()..writeManifest(manifest);

  final result = project.run(args, environment: environment);
  expect(result.exitCode, 0, reason: '$result');

  return project.read('out.properties')!.substring(_header.length);
}

/// Runs [manifest] with [args], expects exit code 1 and nothing written, and
/// returns stderr.
String _fail(String manifest, {List<String> args = const <String>[]}) {
  final project = TestProject.create()..writeManifest(manifest);

  final result = project.run(args);

  expect(result.exitCode, 1, reason: '$result');
  expect(result.err, isNot(contains('#0')), reason: 'no stack trace');
  expect(project.files(), <String>{'livery.yaml'}, reason: 'nothing written');

  return result.err;
}

void main() {
  group('declaring defines', () {
    test('a define with values, a default and dart_class resolves to its default', () {
      expect(
        _render(
          _manifest('  ENV: {values: [dev, production], default: dev, required: false, dart_class: Environment}'),
        ),
        'app_name=Demo\nENV=dev\n',
      );
    });

    test('a bare list is shorthand for values', () {
      expect(
        _render(_manifest('  ENV: [dev, production]'), args: <String>['-D', 'ENV=production']),
        contains('ENV=production'),
      );
      expect(
        _fail(_manifest('  ENV: [dev, production]'), args: <String>['-D', 'ENV=qa']),
        contains('define `ENV` has invalid value `qa`, expected one of dev, production'),
      );
    });

    test('an empty node declares a free-form define', () {
      expect(
        _render(_manifest('  TAG:'), args: <String>['-D', 'TAG=anything at all']),
        contains('TAG=anything at all'),
      );
    });

    test('a define entry rejects unknown keys', () {
      expect(
        _fail(_manifest('  ENV: {values: [dev], defualt: dev}')),
        contains(
          '[defines.ENV.defualt] unknown key `defualt`, accepted keys are dart_class, default, required, values',
        ),
      );
    });

    test('case_sensitive is an unknown key', () {
      expect(
        _fail(_manifest('  ENV: {values: [dev], case_sensitive: true}')),
        contains('[defines.ENV.case_sensitive] unknown key `case_sensitive`'),
      );
    });

    test('a default that is not one of the values fails', () {
      expect(
        _fail(_manifest('  ENV: {values: [dev, production], default: qa}')),
        contains('[defines.ENV.default] default `qa` is not one of dev, production'),
      );
    });

    test('a define that is neither a mapping, a list nor empty fails', () {
      expect(_fail(_manifest('  ENV: dev')), contains('[defines.ENV] expected a mapping, got `dev`'));
    });
  });

  group('sources', () {
    const manifest = '''
  A:
  B:
  C:
  D:
''';

    test('merge key by key, each later source winning', () {
      final project =
          TestProject.create()
            ..writeManifest(_manifest(manifest, extra: 'dart_defines_file: ios/Flutter/Generated.xcconfig'))
            ..write(
              'ios/Flutter/Generated.xcconfig',
              'FLUTTER_ROOT=/flutter\n'
                  'DART_DEFINES=${_payload(const <String, String>{'A': 'file', 'B': 'file', 'C': 'file', 'D': 'file'})}\n'
                  'TRACK_WIDGET_CREATION=true\n',
            );

      final result = project.run(
        <String>[
          '--dart-defines',
          _payload(const <String, String>{'C': 'flag', 'D': 'flag'}),
          '--define',
          'D=define',
        ],
        environment: <String, String>{
          'DART_DEFINES': _payload(const <String, String>{'B': 'env', 'C': 'env', 'D': 'env'}),
        },
      );

      expect(result.exitCode, 0, reason: '$result');
      expect(project.read('out.properties'), '${_header}app_name=Demo\nA=file\nB=env\nC=flag\nD=define\n');
    });

    test('--define is repeatable and never splits its value on commas', () {
      expect(
        _render(_manifest(manifest), args: <String>['-D', 'A=x,y', '--define', 'B=z']),
        'app_name=Demo\nA=x,y\nB=z\n',
      );
    });

    test('a value may contain =', () {
      expect(_render(_manifest(manifest), args: <String>['-D', 'A=k=v']), 'app_name=Demo\nA=k=v\n');
    });

    test('a --define without = is a usage error', () {
      final result = (TestProject.create()..writeManifest(_manifest(manifest))).run(<String>['-D', 'A']);

      expect(result.exitCode, 64, reason: '$result');
      expect(result.err, contains('malformed define `A`, expected KEY=VALUE'));
    });

    test('a missing dart_defines_file is ignored', () {
      expect(
        _render(
          _manifest(manifest, extra: 'dart_defines_file: ios/Flutter/Generated.xcconfig'),
          args: <String>['-D', 'A=1'],
        ),
        'app_name=Demo\nA=1\n',
      );
    });

    test('dart_defines_file resolves against the root', () {
      final project =
          TestProject.create()
            ..write(
              'tools/livery.yaml',
              _manifest(manifest, extra: 'root: ../app\ndart_defines_file: Generated.xcconfig'),
            )
            ..write('app/Generated.xcconfig', 'DART_DEFINES=${_payload(const <String, String>{'A': 'file'})}\n');

      final result = project.run(const <String>['-c', 'tools/livery.yaml']);

      expect(result.exitCode, 0, reason: '$result');
      expect(project.read('app/out.properties'), '${_header}app_name=Demo\nA=file\n');
    });

    test('undeclared input keys are ignored, Flutter reserved ones included', () {
      expect(
        _render(
          _manifest(manifest),
          args: <String>[
            '--dart-defines',
            '${_payload(const <String, String>{'flutter.inspector.structuredErrors': 'true', 'A': '1'})},not base64!',
          ],
          environment: <String, String>{
            'DART_DEFINES': _payload(const <String, String>{'OTHER': 'x'}),
          },
        ),
        'app_name=Demo\nA=1\n',
      );
    });
  });

  group('matching and resolution', () {
    test('values match exactly, and a mismatch names the allowed values', () {
      expect(
        _fail(_manifest('  ENV: [dev, production]'), args: <String>['-D', 'ENV=DEV']),
        contains('define `ENV` has invalid value `DEV`, expected one of dev, production'),
      );
    });

    test('names match exactly; a differently cased name is undeclared input', () {
      expect(
        _render(_manifest('  ENV: {values: [dev, production], default: production}'), args: <String>['-D', 'env=dev']),
        'app_name=Demo\nENV=production\n',
      );
    });

    test('input values are trimmed', () {
      expect(_render(_manifest('  ENV: [dev, production]'), args: <String>['-D', 'ENV= dev ']), contains('ENV=dev\n'));
    });

    test('an empty value counts as absent, also when it overrides an earlier source', () {
      expect(
        _render(
          _manifest('  ENV: {values: [dev, production], default: production}'),
          args: <String>['-D', 'ENV=  '],
          environment: <String, String>{
            'DART_DEFINES': _payload(const <String, String>{'ENV': 'dev'}),
          },
        ),
        'app_name=Demo\nENV=production\n',
      );
    });

    test('a missing required define fails, naming the allowed values', () {
      expect(
        _fail(_manifest('  ENV: {values: [dev, production], required: true}')),
        contains('[defines.ENV] missing required define `ENV` (one of dev, production)'),
      );
    });

    test('a missing required free-form define fails', () {
      expect(
        _fail(_manifest('  TAG: {required: true}'), args: <String>['-D', 'TAG=']),
        contains('missing required define `TAG`'),
      );
    });

    test('an absent optional define without a default stays unresolved and is not injected', () {
      expect(_render(_manifest('  ENV: [dev, production]\n  TAG:')), 'app_name=Demo\n');
    });
  });

  group('injecting into outputs', () {
    test('include_defines is off by default for properties', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
defines:
  ENV: {values: [dev], default: dev}
config:
  android: {app_name: Demo}
outputs:
  android:
    files: [out.properties]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('out.properties'), '${_header}app_name=Demo\n');
    });

    test('injected defines follow the declaration order and are escaped like config', () {
      expect(
        _render(_manifest('  B:\n  A:'), args: <String>['-D', 'A=x', '-D', r'B=C:\temp']),
        'app_name=Demo\nB=C:\\\\temp\nA=x\n',
      );
    });

    test('a define named like a merged config key fails', () {
      expect(
        _fail(_manifest('  app_name:'), args: <String>['-D', 'app_name=Other']),
        contains('[outputs.android] define `app_name` has the same name as a config key; rename one of them'),
      );
    });

    test('a define named like a nested config mapping fails, resolved or not', () {
      final err = _fail('''
version: 1
defines:
  api:
config:
  android:
    api: {url: https://example.com}
outputs:
  android:
    include_defines: true
    files: [out.properties]
''');

      expect(err, contains('define `api` has the same name as a config key'));
    });

    test('a define named like a config key does not fail without include_defines', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
defines:
  app_name:
config:
  android: {app_name: Demo}
outputs:
  android:
    files: [out.properties]
''');

      expect(project.run(const <String>['-D', 'app_name=Other']).exitCode, 0);
    });
  });
}
