import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';

import 'support/test_project.dart';

/// Runs a manifest whose `config` is [config] and whose single output `out`,
/// in [format], has the extra keys [output], writing `out.txt`.
(TestProject, CliResult) _run(String format, String config, {String output = '', String defines = ''}) {
  final project =
      TestProject.create()..writeManifest('''
version: 1
$defines
config:
$config
outputs:
  out:
    format: $format
    files: [out.txt]
$output
''');

  return (project, project.run(const <String>[]));
}

/// The file [_run] writes, expecting the run to succeed.
String _render(String format, String config, {String output = '', String defines = ''}) {
  final (project, result) = _run(format, config, output: output, defines: defines);
  expect(result.exitCode, 0, reason: '$result');

  return project.read('out.txt')!;
}

/// The error output of [_run], expecting the run to fail without writing.
String _fail(String format, String config, {String output = '', String defines = ''}) {
  final (project, result) = _run(format, config, output: output, defines: defines);
  expect(result.exitCode, 1, reason: '$result');
  expect(project.exists('out.txt'), isFalse);

  return result.err;
}

/// The file [_render] writes after the generated header with [commentPrefix].
String _body(String format, String commentPrefix, String config, {String output = ''}) {
  final header =
      '$commentPrefix GENERATED BY livery. Do not edit by hand.\n'
      '$commentPrefix Regenerate with `dart run livery`.\n'
      '\n';
  final contents = _render(format, config, output: output);
  expect(contents, startsWith(header));

  return contents.substring(header.length);
}

void main() {
  group('xcconfig', () {
    String body(String config, {String output = ''}) => _body('xcconfig', '//', config, output: output);

    test('writes one KEY=value line per value after a `//` header', () {
      expect(
        body('''
  out:
    APP_NAME: Demo
    api:
      timeout: 30
'''),
        'APP_NAME=Demo\n'
        'api_timeout=30\n',
      );
    });

    test(r'`//` in a value is broken up with `$()`, so Xcode does not read a comment', () {
      expect(
        body('  out: {API_URL: "https://api.example.com//v1"}'),
        r'API_URL=https:/$()/api.example.com/$()/v1'
        '\n',
      );
    });

    test('a run of slashes keeps no `//`', () {
      expect(
        body('  out: {PATH: "a///b"}'),
        r'PATH=a/$()/$()/b'
        '\n',
      );
    });

    test('a dot in a key becomes `__`', () {
      expect(body('  out: {"com.example.key": a}'), 'com__example__key=a\n');
    });

    test('a key that is not an identifier fails, naming the config key', () {
      expect(
        _fail('xcconfig', '  out: {app-name: a}'),
        contains(
          '[outputs.out] config key `app-name` is not a valid xcconfig key; '
          'a key must match `[A-Za-z_][A-Za-z0-9_]*`',
        ),
      );
    });

    test('a key that becomes invalid once joined fails, naming what it became', () {
      expect(
        _fail('xcconfig', '  out: {api: {url: a}}', output: '    separator: "-"'),
        contains('config key `api.url` becomes `api-url`, which is not a valid xcconfig key'),
      );
    });

    test('a key starting with a digit fails', () {
      expect(_fail('xcconfig', '  out: {1st: a}'), contains('config key `1st` is not a valid xcconfig key'));
    });

    test('a dotted key that collides with a key holding `__` fails, naming both', () {
      expect(
        _fail('xcconfig', '  out: {"a.b": dotted, a__b: plain}'),
        contains('config keys `"a.b"` and `a__b` both become `a__b`'),
      );
    });

    test('a line break in a value fails, since an xcconfig value is one line', () {
      expect(
        _fail('xcconfig', r'  out: {NOTE: "a\nb"}'),
        contains('[outputs.out] config key `NOTE` holds a line break, which an xcconfig value cannot'),
      );
    });

    test('a carriage return in a value fails too', () {
      expect(_fail('xcconfig', r'  out: {NOTE: "a\rb"}'), contains('config key `NOTE` holds a line break'));
    });

    test('flatten: false rejects a nested mapping', () {
      expect(
        _fail('xcconfig', '  out: {api: {url: a}}', output: '    flatten: false'),
        contains('`api` is a mapping, which an output with `flatten: false` cannot write'),
      );
    });
  });

  group('env', () {
    String body(String config, {String output = ''}) => _body('env', '#', config, output: output);

    test('writes plain values unquoted after a `#` header', () {
      expect(
        body('''
  out:
    APP_NAME: Demo
    api:
      url: https://api.example.com/v1
      timeout: 30
    empty: null
'''),
        'APP_NAME=Demo\n'
        'api_url=https://api.example.com/v1\n'
        'api_timeout=30\n'
        'empty=\n',
      );
    });

    test('a value holding anything else is single-quoted', () {
      expect(
        body(r'''
  out:
    SPACED: a b
    DOLLAR: $HOME
    BACKSLASH: C:\keys
    NEWLINE: "a\nb"
    QUERY: "?a"
'''),
        "SPACED='a b'\n"
        r"DOLLAR='$HOME'"
        '\n'
        r"BACKSLASH='C:\keys'"
        '\n'
        "NEWLINE='a\nb'\n"
        "QUERY='?a'\n",
      );
    });

    test(r"a single quote closes the quotes, adds `\'` and reopens them", () {
      expect(body('''  out: {QUOTED: "it's"}'''), "QUOTED='it'\\''s'\n");
    });

    test('a shell reads back exactly the configured values', () {
      const values = <String, String>{
        'URL': 'https://api.example.com/v1?a=b&c=d',
        'BACKSLASH': r'C:\keys\release.jks',
        'NEWLINE': 'a\nb',
        'LEADING': ' a',
        'QUOTES': '''say "hi" it's''',
        'DOLLAR': r'$HOME $(id) `id`',
      };
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  out:
${values.entries.map((entry) => '    ${entry.key}: ${jsonEncode(entry.value)}').join('\n')}
outputs:
  out:
    format: env
    files: [out.env]
''');
      expect(project.run(const <String>[]).exitCode, 0);

      for (final MapEntry(:key, :value) in values.entries) {
        final shell = Process.runSync('/bin/sh', <String>[
          '-c',
          '. ./out.env && printf %s "\$$key"',
        ], workingDirectory: project.root);
        expect(shell.stdout, value, reason: '$key: ${shell.stderr}');
      }
    }, testOn: 'posix');

    test('a dot in a key becomes `__`', () {
      expect(body('  out: {"com.example.key": a}'), 'com__example__key=a\n');
    });

    test('a dotted key that collides with a key holding `__` fails, naming both', () {
      expect(
        _fail('env', '  out: {"a.b": dotted, a__b: plain}'),
        contains('config keys `"a.b"` and `a__b` both become `a__b`'),
      );
    });

    test('a key that is not an identifier fails, naming the config key', () {
      expect(_fail('env', '  out: {app-name: a}'), contains('config key `app-name` is not a valid env key'));
    });

    test('flatten: false rejects a nested mapping', () {
      expect(
        _fail('env', '  out: {api: {url: a}}', output: '    flatten: false'),
        contains('`api` is a mapping, which an output with `flatten: false` cannot write'),
      );
    });
  });

  group('json', () {
    const typed = '''
  out:
    name: Demo
    api:
      url: https://api.example.com
      timeout: 30
      ratio: 1.5
    debug: false
    none: null
    tags: [a, 1, true, null]
''';

    test('writes the merged config nested, keeping value types, with no header', () {
      expect(
        _render('json', typed),
        '{\n'
        '  "name": "Demo",\n'
        '  "api": {\n'
        '    "url": "https://api.example.com",\n'
        '    "timeout": 30,\n'
        '    "ratio": 1.5\n'
        '  },\n'
        '  "debug": false,\n'
        '  "none": null,\n'
        '  "tags": [\n'
        '    "a",\n'
        '    1,\n'
        '    true,\n'
        '    null\n'
        '  ]\n'
        '}\n',
      );
    });

    test('flatten: true joins nested keys with the separator', () {
      expect(jsonDecode(_render('json', typed, output: '    flatten: true\n    separator: "."')), <String, Object?>{
        'name': 'Demo',
        'api.url': 'https://api.example.com',
        'api.timeout': 30,
        'api.ratio': 1.5,
        'debug': false,
        'none': null,
        'tags': <Object?>['a', 1, true, null],
      });
    });

    test('flatten: true fails when two keys become the same key', () {
      expect(
        _fail('json', '  out: {api: {url: a}, api_url: b}', output: '    flatten: true'),
        contains('config keys `api.url` and `api_url` both become `api_url`'),
      );
    });

    test('a value JSON cannot hold fails', () {
      expect(_fail('json', '  out: {ratio: .nan}'), contains('config key `ratio` is NaN, which JSON cannot hold'));
    });

    test('an infinite value fails', () {
      expect(_fail('json', '  out: {big: -.inf}'), contains('config key `big` is infinite, which JSON cannot hold'));
    });

    test('NaN inside a list fails', () {
      expect(_fail('json', '  out: {list: [1.5, .nan]}'), contains('config key `list` is NaN, which JSON cannot hold'));
    });

    test('a double keeps its decimal point', () {
      expect(jsonDecode(_render('json', '  out: {two: 2.0}')), <String, Object?>{'two': 2.0});
      expect(_render('json', '  out: {two: 2.0}'), contains('"two": 2.0'));
    });

    test('text is escaped as JSON requires', () {
      const text = 'https://x.com/a b\\c\nd "q" \$e \u0001';
      expect(jsonDecode(_render('json', '  out: {text: ${jsonEncode(text)}}')), <String, Object?>{'text': text});
    });
  });

  group('include_defines', () {
    const defines = '''
defines:
  ENV: {values: [dev, production], default: dev}
  BUILD_TAG:
''';

    test('is off by default in every key-value format', () {
      for (final format in <String>['xcconfig', 'env', 'json']) {
        expect(_render(format, '  out: {A: a}', defines: defines), isNot(contains('ENV')), reason: format);
      }
    });

    test('xcconfig writes resolved defines after the config, leaving out unresolved ones', () {
      expect(
        _render('xcconfig', '  out: {A: a}', defines: defines, output: '    include_defines: true'),
        endsWith('A=a\nENV=dev\n'),
      );
    });

    test('env writes resolved defines after the config, leaving out unresolved ones', () {
      expect(
        _render('env', '  out: {A: a}', defines: defines, output: '    include_defines: true'),
        endsWith('A=a\nENV=dev\n'),
      );
    });

    test('json writes resolved defines as top-level strings, leaving out unresolved ones', () {
      expect(
        jsonDecode(_render('json', '  out: {api: {url: u}}', defines: defines, output: '    include_defines: true')),
        <String, Object?>{
          'api': <String, Object?>{'url': 'u'},
          'ENV': 'dev',
        },
      );
    });

    test('a define named like a top-level config key fails in every key-value format', () {
      for (final format in <String>['xcconfig', 'env', 'json']) {
        expect(
          _fail(format, '  out: {ENV: {x: a}}', defines: defines, output: '    include_defines: true'),
          contains('[outputs.out] define `ENV` has the same name as a config key; rename one of them'),
          reason: format,
        );
      }
    });
  });
}
