import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '// GENERATED BY livery. Do not edit by hand.\n'
    '// Regenerate with `dart run livery`.\n'
    '\n';

const _emptyConfig = 'config:\n  android: {}';

const _file = 'android/livery/src/main/kotlin/LiveryConfig.kt';

/// Runs a manifest with [defines] and [config] whose single `kotlin` output
/// `android` has the extra keys [output] and writes [_file].
///
/// The output merges the section `android`, which [config] holds empty by
/// default.
(TestProject, CliResult) _run({
  String defines = '',
  String config = _emptyConfig,
  String output = '',
  List<String> args = const <String>[],
}) {
  final project =
      TestProject.create()..writeManifest('''
version: 1
$defines
$config
outputs:
  android:
    format: kotlin
    files: [$_file]
$output
''');

  return (project, project.run(args));
}

/// The file [_run] writes after the header, expecting the run to succeed.
String _body({
  String defines = '',
  String config = _emptyConfig,
  String output = '',
  List<String> args = const <String>[],
}) {
  final (project, result) = _run(defines: defines, config: config, output: output, args: args);
  expect(result.exitCode, 0, reason: '$result');
  final contents = project.read(_file)!;
  expect(contents, startsWith(_header));

  return contents.substring(_header.length);
}

/// The error output of [_run], expecting the run to fail without writing.
String _fail({String defines = '', String config = _emptyConfig, String output = ''}) {
  final (project, result) = _run(defines: defines, config: config, output: output);
  expect(result.exitCode, 1, reason: '$result');
  expect(project.exists(_file), isFalse);

  return result.err;
}

/// [_body] with only `config: {android: <android>}`.
String _configBody(String android) => _body(config: 'config:\n  android: $android');

/// [_fail] with only `config: {android: <android>}`.
String _configFail(String android) => _fail(config: 'config:\n  android: $android');

void main() {
  group('object', () {
    test('holds enums, defines and config constants, in that order', () {
      expect(
        _body(
          defines: '''
defines:
  ENV: {values: [dev, staging, production], default: dev}
  BUILD_TAG:
''',
          config: '''
config:
  android:
    app_id: com.example.demo
    version_code: 42
    ratio: 1.5
    minify: false
''',
          args: const <String>['-D', 'BUILD_TAG=local'],
        ),
        '''
object LiveryConfig {
    enum class Env { DEV, STAGING, PRODUCTION }

    val ENV: Env = Env.DEV
    val BUILD_TAG: String? = "local"

    const val APP_ID: String = "com.example.demo"
    const val VERSION_CODE: Int = 42
    const val RATIO: Double = 1.5
    const val MINIFY: Boolean = false
}
''',
      );
    });

    test('has no body when it would hold nothing', () {
      expect(_body(), 'object LiveryConfig\n');
    });

    test('is named after the file', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  android: {a: 1}
outputs:
  android:
    format: kotlin
    files: [a/BuildValues.kt, b/BuildValues.kt]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('a/BuildValues.kt'), contains('object BuildValues {'));
      expect(project.read('b/BuildValues.kt'), project.read('a/BuildValues.kt'));
    });

    for (final name in <String>['my-config', '1st', 'object', '__', 'Live.ry']) {
      test('a file name `$name` that is not a Kotlin identifier fails', () {
        final project =
            TestProject.create()..writeManifest('''
version: 1
outputs:
  android:
    format: kotlin
    files: [kotlin/$name.kt]
''');

        final result = project.run(const <String>[]);

        expect(result.exitCode, 1);
        expect(
          result.err,
          contains(
            '[outputs.android.files] `$name` is not a valid Kotlin identifier, '
            'and a kotlin output names its object after the file',
          ),
        );
      });
    }

    test('files with different names fail, naming both', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
outputs:
  android:
    format: kotlin
    files: [a/LiveryConfig.kt, b/Other.kt]
''');

      final result = project.run(const <String>[]);

      expect(result.exitCode, 1);
      expect(
        result.err,
        contains(
          '[outputs.android.files] `a/LiveryConfig.kt` and `b/Other.kt` have different names, '
          'and every file of a kotlin output must have the same one',
        ),
      );
    });
  });

  group('defines', () {
    test('a constrained define becomes an enum class and a property holding its value', () {
      expect(
        _body(
          defines: 'defines:\n  ENV: {values: [dev, production], required: true}',
          args: const <String>['-D', 'ENV=production'],
        ),
        'object LiveryConfig {\n'
        '    enum class Env { DEV, PRODUCTION }\n'
        '\n'
        '    val ENV: Env = Env.PRODUCTION\n'
        '}\n',
      );
    });

    test('a define with a default is non-null', () {
      expect(
        _body(defines: 'defines:\n  FLAVOR: {values: [free, paid], default: free}\n  TAG: {default: x}'),
        contains('    val FLAVOR: Flavor = Flavor.FREE\n    val TAG: String = "x"\n'),
      );
    });

    test('a required free-form define is non-null', () {
      expect(
        _body(defines: 'defines:\n  TAG: {required: true}', args: const <String>['-D', 'TAG=nightly']),
        contains('    val TAG: String = "nightly"\n'),
      );
    });

    test('an optional define is nullable and holds null when unresolved', () {
      expect(
        _body(defines: 'defines:\n  FLAVOR: [free, paid]\n  TAG:'),
        contains('    val FLAVOR: Flavor? = null\n    val TAG: String? = null\n'),
      );
    });

    test('an optional define stays nullable when it has a value', () {
      expect(
        _body(defines: 'defines:\n  FLAVOR: [free, paid]', args: const <String>['-D', 'FLAVOR=paid']),
        contains('    val FLAVOR: Flavor? = Flavor.PAID\n'),
      );
    });

    test('names follow UPPER_SNAKE for properties and constants and UpperCamel for enum types', () {
      expect(
        _body(defines: 'defines:\n  build-mode: {values: [app-store, playStore, PLAY_BETA, 1x], default: 1x}'),
        contains(
          '    enum class BuildMode { APP_STORE, PLAY_STORE, PLAY_BETA, _1X }\n'
          '\n'
          '    val BUILD_MODE: BuildMode = BuildMode._1X\n',
        ),
      );
    });

    test('a define name starting with a digit gets a `_` prefix', () {
      expect(
        _body(defines: 'defines:\n  2FA: {values: [on], default: on}'),
        contains('    enum class _2fa { ON }\n\n    val _2FA: _2fa = _2fa.ON\n'),
      );
    });

    test('a define that declares no values becomes an empty enum', () {
      expect(
        _body(defines: 'defines:\n  MODE: []'),
        contains('    enum class Mode {}\n\n    val MODE: Mode? = null\n'),
      );
    });

    test('include_defines: false leaves the defines out', () {
      expect(
        _body(
          defines: 'defines:\n  ENV: [dev]\n  TAG:',
          config: 'config:\n  android: {a: 1}',
          output: '    include_defines: false',
        ),
        'object LiveryConfig {\n    const val A: Int = 1\n}\n',
      );
    });

    test('values that become one constant fail, naming both', () {
      expect(
        _fail(defines: 'defines:\n  MODE: [a-b, a_b]'),
        contains('[outputs.android] define `MODE` values `a-b` and `a_b` both become the Kotlin enum constant `A_B`'),
      );
    });

    test('a value with no letter or digit fails', () {
      expect(
        _fail(defines: 'defines:\n  MODE: [a, "-"]'),
        contains('[outputs.android] define `MODE` value `-` becomes `_`, which is not a usable Kotlin name'),
      );
    });

    for (final (name, type) in <(String, String)>[
      ('STRING', 'String'),
      ('int', 'Int'),
      ('DOUBLE', 'Double'),
      ('boolean', 'Boolean'),
      ('ANY', 'Any'),
      ('nothing', 'Nothing'),
      ('UNIT', 'Unit'),
    ]) {
      test('a define whose enum would be named `$type` fails', () {
        expect(
          _fail(defines: 'defines:\n  $name: [a]'),
          contains(
            '[outputs.android] define `$name` becomes the enum class `$type`, '
            'which hides the Kotlin type `$type`; rename the define',
          ),
        );
      });
    }

    test('a define whose enum and property share a name fails', () {
      expect(
        _fail(defines: 'defines:\n  X: [a]'),
        contains('[outputs.android] the enum class of define `X` and define `X` both become `X` in `LiveryConfig`'),
      );
    });
  });

  group('config', () {
    test('keys are named after the flattened path in UPPER_SNAKE', () {
      expect(
        _configBody('{app: {id: x, versionName: "1.0"}, "dotted.key": y, 2fa: true, "a b": z}'),
        contains(
          '    const val APP_ID: String = "x"\n'
          '    const val APP_VERSION_NAME: String = "1.0"\n'
          '    const val DOTTED_KEY: String = "y"\n'
          '    const val _2FA: Boolean = true\n'
          '    const val A_B: String = "z"\n',
        ),
      );
    });

    test('merges the section named after the output by default', () {
      expect(
        _body(config: 'config:\n  common: {a: 1}\n  android: {b: 2}'),
        'object LiveryConfig {\n    const val B: Int = 2\n}\n',
      );
    });

    test('merge names the sections to merge', () {
      expect(
        _body(config: 'config:\n  common: {a: 1}\n  android: {b: 2}', output: '    merge: [common, android]'),
        contains('    const val A: Int = 1\n    const val B: Int = 2\n'),
      );
    });

    test('two keys that become one name fail, naming both', () {
      expect(
        _configFail('{api_url: a, api: {url: b}}'),
        contains(
          '[outputs.android] config key `api_url` and config key `api.url` both become `API_URL` in `LiveryConfig`',
        ),
      );
    });

    test('a define and a config key that become one name fail, naming both', () {
      expect(
        _fail(defines: 'defines:\n  BUILD_TAG:', config: 'config:\n  android: {build_tag: a}'),
        contains(
          '[outputs.android] define `BUILD_TAG` and config key `build_tag` both become `BUILD_TAG` in `LiveryConfig`',
        ),
      );
    });

    test('a config key with no letter or digit fails', () {
      expect(
        _configFail('{"-": a}'),
        contains('[outputs.android] config key `-` becomes `_`, which is not a usable Kotlin name'),
      );
    });
  });

  group('literals', () {
    test(r'strings escape backslash, quote, $, line breaks and tabs, and other control characters as \u', () {
      expect(
        _configBody(r'''{text: "it's $HOME \\ \"q\"\n\r\t\u0001\u007f\u0085 é"}'''),
        contains(r'''    const val TEXT: String = "it's \$HOME \\ \"q\"\n\r\t\u0001\u007f\u0085 é"'''),
      );
    });

    test('ints at the 32-bit limits are written as they are', () {
      expect(
        _configBody('{max: 2147483647, min: -2147483648}'),
        contains('    const val MAX: Int = 2147483647\n    const val MIN: Int = -2147483648\n'),
      );
    });

    for (final value in <String>['2147483648', '-2147483649']) {
      test('an int $value outside the 32-bit range fails, naming the key', () {
        expect(
          _configFail('{big: $value}'),
          contains('[outputs.android] config key `big` is $value, outside the range of a Kotlin Int'),
        );
      });
    }

    test('doubles always carry a decimal point or exponent', () {
      expect(
        _configBody('{whole: 2.0, big: 1e21, small: -1.5e-7}'),
        contains(
          '    const val WHOLE: Double = 2.0\n'
          '    const val BIG: Double = 1e+21\n'
          '    const val SMALL: Double = -1.5e-7\n',
        ),
      );
    });

    for (final (description, value, message) in <(String, String, String)>[
      ('null', 'null', 'config key `c_key` is null, which a kotlin output cannot hold'),
      ('a list', '[a, b]', 'config key `c_key` is a list, which a kotlin output cannot hold'),
      ('NaN', '.nan', 'config key `c_key` is NaN, which a kotlin output cannot hold'),
      ('infinite', '-.inf', 'config key `c_key` is infinite, which a kotlin output cannot hold'),
    ]) {
      test('a value that is $description fails, naming the key', () {
        expect(_configFail('{c_key: $value}'), contains('[outputs.android] $message'));
      });
    }

    test('define values are escaped like config strings', () {
      expect(
        _body(defines: 'defines:\n  TAG:', args: const <String>['-D', r'TAG=a"$b']),
        contains(r'    val TAG: String? = "a\"\$b"'),
      );
    });
  });

  group('options', () {
    for (final key in <String>['class_name: Config', 'flatten: true', 'separator: "-"']) {
      final name = key.split(':').first;
      test('`$name` is rejected', () {
        expect(
          _fail(output: '    $key'),
          contains(
            '[outputs.android.$name] unknown key `$name`, accepted keys are files, format, include_defines, merge',
          ),
        );
      });
    }
  });
}
