import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '# GENERATED BY livery. Do not edit by hand.\n'
    '# Regenerate with `dart run livery`.\n'
    '\n';

/// A manifest with the defines `ENV` (dev, staging, production; default dev)
/// and `FLAVOR` (free, paid; default free), the `android` section [config],
/// the `overrides` list [overrides] and one properties output of `android`.
String _manifest({required String config, required String overrides}) => '''
version: 1
defines:
  ENV: {values: [dev, staging, production], default: dev}
  FLAVOR: {values: [free, paid], default: free}
config:
  android:
$config
overrides:
$overrides
outputs:
  android:
    files: [out.properties]
''';

/// Runs [manifest] with [args] and returns the written file body after the
/// header.
String _render(String manifest, {List<String> args = const <String>[]}) {
  final project = TestProject.create()..writeManifest(manifest);

  final result = project.run(args);
  expect(result.exitCode, 0, reason: '$result');

  return project.read('out.properties')!.substring(_header.length);
}

/// Runs [manifest] with [args], expects exit code 1 and nothing written, and
/// returns stderr.
String _fail(String manifest, {List<String> args = const <String>[]}) {
  final project = TestProject.create()..writeManifest(manifest);

  final result = project.run(args);

  expect(result.exitCode, 1, reason: '$result');
  expect(result.err, isNot(contains('#0')), reason: 'no stack trace');
  expect(project.files(), <String>{'livery.yaml'}, reason: 'nothing written');

  return result.err;
}

void main() {
  group('selectors', () {
    final manifest = _manifest(
      config: '    url: dev.example.com',
      overrides: '''
  - when: {ENV: production}
    set:
      android: {url: example.com}
''',
    );

    test('an override applies when its selector matches the defines', () {
      expect(_render(manifest, args: <String>['-D', 'ENV=production']), 'url=example.com\n');
    });

    test('an override does not apply when its selector does not match', () {
      expect(_render(manifest), 'url=dev.example.com\n');
    });

    test('a list selects any of its values', () {
      final manifest = _manifest(
        config: '    url: dev.example.com',
        overrides: '''
  - when: {ENV: [staging, production]}
    set:
      android: {url: example.com}
''',
      );

      expect(_render(manifest, args: <String>['-D', 'ENV=staging']), 'url=example.com\n');
      expect(_render(manifest, args: <String>['-D', 'ENV=production']), 'url=example.com\n');
      expect(_render(manifest), 'url=dev.example.com\n');
    });

    test('selectors on two defines must both match', () {
      final manifest = _manifest(
        config: '    ads: false',
        overrides: '''
  - when: {ENV: production, FLAVOR: free}
    set:
      android: {ads: true}
''',
      );

      expect(_render(manifest, args: <String>['-D', 'ENV=production', '-D', 'FLAVOR=free']), 'ads=true\n');
      expect(_render(manifest, args: <String>['-D', 'ENV=production', '-D', 'FLAVOR=paid']), 'ads=false\n');
      expect(_render(manifest, args: <String>['-D', 'ENV=dev', '-D', 'FLAVOR=free']), 'ads=false\n');
    });

    test('a selector on an unresolved define does not match', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
defines:
  ENV: [dev, production]
config:
  android: {url: dev.example.com}
overrides:
  - when: {ENV: production}
    set:
      android: {url: example.com}
outputs:
  android: {files: [out.properties]}
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('out.properties'), endsWith('url=dev.example.com\n'));
    });

    test('an empty or missing when matches everything', () {
      final manifest = _manifest(
        config: '    a: base\n    b: base',
        overrides: '''
  - when: {}
    set:
      android: {a: empty}
  - set:
      android: {b: missing}
''',
      );

      expect(_render(manifest), 'a=empty\nb=missing\n');
    });

    test('a selector with no values fails', () {
      final manifest = _manifest(
        config: '    a: base',
        overrides: '''
  - when: {ENV: []}
    set:
      android: {a: x}
''',
      );

      expect(_fail(manifest), contains('[overrides[0].when.ENV] the selector on `ENV` lists no values'));
    });

    test('an empty selector node fails', () {
      final manifest = _manifest(
        config: '    a: base',
        overrides: '''
  - when: {ENV: }
    set:
      android: {a: x}
''',
      );

      expect(_fail(manifest), contains('[overrides[0].when.ENV] the selector on `ENV` lists no values'));
    });

    test('a selector naming an undeclared define fails, also when the name differs only by case', () {
      final manifest = _manifest(
        config: '    a: base',
        overrides: '''
  - when: {env: dev}
    set:
      android: {a: x}
''',
      );

      expect(
        _fail(manifest),
        contains('[overrides[0].when.env] `env` is not a declared define; declared defines are ENV, FLAVOR'),
      );
    });

    test('a selector value outside the define values fails, also when it differs only by case', () {
      final manifest = _manifest(
        config: '    a: base',
        overrides: '''
  - when: {ENV: [dev, Production]}
    set:
      android: {a: x}
''',
      );

      expect(
        _fail(manifest),
        contains(
          '[overrides[0].when.ENV[1]] `Production` is not a value of define `ENV`, expected one of dev, staging, production',
        ),
      );
    });

    test('a free-form define accepts any selector value', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
defines:
  BUILD_TAG:
config:
  android: {tag: none}
overrides:
  - when: {BUILD_TAG: nightly}
    set:
      android: {tag: nightly}
outputs:
  android: {files: [out.properties]}
''');

      expect(project.run(const <String>['-D', 'BUILD_TAG=nightly']).exitCode, 0);
      expect(project.read('out.properties'), endsWith('tag=nightly\n'));
    });
  });

  group('applying overrides', () {
    test('matching overrides apply in declaration order, the last one winning', () {
      final manifest = _manifest(
        config: '    a: base\n    b: base\n    c: base',
        overrides: '''
  - when: {ENV: production}
    set:
      android: {a: first, b: first}
  - when: {FLAVOR: paid}
    set:
      android: {b: second, c: second}
''',
      );

      expect(
        _render(manifest, args: <String>['-D', 'ENV=production', '-D', 'FLAVOR=paid']),
        'a=first\nb=second\nc=second\n',
      );
    });

    test('mappings merge key by key and lists are replaced', () {
      final manifest = _manifest(
        config: '''
    api:
      url: dev.example.com
      timeout: 30
    hosts: [a, b, c]''',
        overrides: '''
  - when: {ENV: production}
    set:
      android:
        api: {url: example.com}
        hosts: [z]
''',
      );

      expect(
        _render(manifest, args: <String>['-D', 'ENV=production']),
        'api_url=example.com\napi_timeout=30\nhosts=z\n',
      );
    });

    test('overrides keep the base key order', () {
      final manifest = _manifest(
        config: '    a: base\n    b: base',
        overrides: '''
  - set:
      android: {b: x, a: y}
''',
      );

      expect(_render(manifest), 'a=y\nb=x\n');
    });

    test('an override reaches every section', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  common: {name: Demo}
  android: {id: com.example}
overrides:
  - set:
      common: {name: Demo Pro}
      android: {id: com.example.pro}
outputs:
  android:
    merge: [common, android]
    files: [out.properties]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('out.properties'), endsWith('name=Demo Pro\nid=com.example.pro\n'));
    });
  });

  group('override entries', () {
    test('overrides must be a list', () {
      expect(
        _fail(_manifest(config: '    a: base', overrides: '  when: {}')),
        contains('[overrides] expected a list, got a mapping'),
      );
    });

    test('an override entry rejects unknown keys', () {
      final manifest = _manifest(
        config: '    a: base',
        overrides: '''
  - when: {}
    sett:
      android: {a: x}
''',
      );

      expect(_fail(manifest), contains('[overrides[0].sett] unknown key `sett`, accepted keys are set, when'));
    });
  });

  group('override checks', () {
    test('a path missing from the base config fails, also when the override does not match', () {
      final manifest = _manifest(
        config: '    api: {url: dev.example.com}',
        overrides: '''
  - when: {ENV: production}
    set:
      android:
        api: {ulr: example.com}
      ios: {name: Demo}
''',
      );

      expect(
        _fail(manifest),
        allOf(
          contains('[overrides] overrides must only set keys of the base config, with the same value types:'),
          contains('  overrides[0].set: `android.api.ulr` is not in the base config\n'),
          contains('  overrides[0].set: `ios` is not in the base config\n'),
        ),
      );
    });

    test('a value of another kind fails, listing every offending path', () {
      final manifest = _manifest(
        config: '''
    name: Demo
    code: 1
    ratio: 1.5
    minify: true
    hosts: [a]
    api: {url: x}
    empty: null''',
        overrides: '''
  - when: {ENV: production}
    set:
      android:
        name: 2
        code: 1.5
        ratio: 2
        minify: yes
        hosts: a
        api: x
  - when: {ENV: staging}
    set:
      android:
        empty: something
''',
      );

      final err = _fail(manifest);

      expect(
        err,
        contains('  overrides[0].set: `android.name` is a string in the base config, got an int; quote it\n'),
      );
      expect(err, contains('  overrides[0].set: `android.code` is an int in the base config, got a double\n'));
      expect(
        err,
        contains('  overrides[0].set: `android.ratio` is a double in the base config, got an int; write `2.0`\n'),
      );
      expect(err, contains('  overrides[0].set: `android.minify` is a bool in the base config, got a string\n'));
      expect(err, contains('  overrides[0].set: `android.hosts` is a list in the base config, got a string\n'));
      expect(err, contains('  overrides[0].set: `android.api` is a mapping in the base config, got a string\n'));
      expect(err, contains('  overrides[1].set: `android.empty` is null in the base config, got a string\n'));
    });

    test('a whole double suggests the int it stands for', () {
      final manifest = _manifest(
        config: '    code: 1',
        overrides: '''
  - set:
      android: {code: 2.0}
''',
      );

      expect(_fail(manifest), contains('`android.code` is an int in the base config, got a double; write `2`'));
    });

    test('a path holding a dot is quoted', () {
      final manifest = _manifest(
        config: '    "org.gradle.jvmargs": -Xmx4G',
        overrides: '''
  - set:
      android: {"org.gradle.jvmarg": -Xmx2G}
''',
      );

      expect(_fail(manifest), contains('`android."org.gradle.jvmarg"` is not in the base config'));
    });

    test('a set that is not a mapping fails', () {
      final manifest = _manifest(config: '    a: base', overrides: '  - set: [a]');

      expect(_fail(manifest), contains('[overrides[0].set] expected a mapping, got a list'));
    });
  });

  group('merged sections', () {
    test('the same key with different kinds in two merged sections fails', () {
      final err = _fail('''
version: 1
config:
  common:
    timeout: 30
    api: {url: x}
  android:
    timeout: "30"
    api: x
outputs:
  android:
    merge: [common, android]
    files: [out.properties]
''');

      expect(
        err,
        contains('[outputs.android] `timeout` is an int in section `common` but a string in section `android`'),
      );
    });

    test('a nested mapping replaced by a scalar fails', () {
      final err = _fail('''
version: 1
config:
  common:
    api: {url: x}
  android:
    api: x
outputs:
  android:
    merge: [common, android]
    files: [out.properties]
''');

      expect(err, contains('`api` is a mapping in section `common` but a string in section `android`'));
    });

    test('the same key with the same kind merges', () {
      final project =
          TestProject.create()..writeManifest('''
version: 1
config:
  common: {timeout: 30, api: {url: x, retries: 1}}
  android: {timeout: 60, api: {url: y}}
outputs:
  android:
    merge: [common, android]
    files: [out.properties]
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('out.properties'), endsWith('timeout=60\napi_url=y\napi_retries=1\n'));
    });
  });
}
