import 'package:test/test.dart';

import 'support/test_project.dart';

const _header =
    '# GENERATED BY livery. Do not edit by hand.\n'
    '# Regenerate with `dart run livery`.\n'
    '\n';

/// Runs a manifest whose `config` is [config] and whose single output
/// `android` has the extra keys [output], and returns the written file body
/// after the header.
String _render(String config, {String output = ''}) {
  final project =
      TestProject.create()..writeManifest('''
config:
$config
outputs:
  android:
    files: [out.properties]
$output
''');

  final result = project.run(const <String>[]);
  expect(result.exitCode, 0, reason: '$result');
  final contents = project.read('out.properties')!;
  expect(contents, startsWith(_header));

  return contents.substring(_header.length);
}

void main() {
  test('writes an inline config section to a properties file', () {
    final project =
        TestProject.create()..writeManifest('''
version: 1
config:
  android:
    app_name: Demo
outputs:
  android:
    files: [android/livery.properties]
''');

    final result = project.run(const <String>[]);

    expect(result.exitCode, 0, reason: '$result');
    expect(project.read('android/livery.properties'), '${_header}app_name=Demo\n');
  });

  group('merge', () {
    test('defaults to the section named after the output', () {
      expect(
        _render('''
  common:
    app_name: Common
  android:
    app_id: com.example
'''),
        'app_id=com.example\n',
      );
    });

    test('merges sections left to right, deeply, a later section winning', () {
      expect(
        _render('''
  common:
    app_name: Common
    api:
      url: https://common
      timeout: 5
    tags: [a, b]
  android:
    app_name: Android
    api:
      url: https://android
    tags: [c]
''', output: '    merge: [common, android]'),
        'app_name=Android\n'
        'api_url=https://android\n'
        'api_timeout=5\n'
        'tags=c\n',
      );
    });

    test('an empty merge writes only the header', () {
      expect(_render('  android:\n    a: b', output: '    merge: []'), '');
    });
  });

  group('format', () {
    test('defaults to properties', () {
      expect(_render('  android:\n    a: b', output: '    format: properties'), 'a=b\n');
    });
  });

  group('files', () {
    test('accepts a single path and writes identical content to every listed file', () {
      final project =
          TestProject.create()..writeManifest('''
config:
  android:
    a: b
  ios:
    c: d
outputs:
  android:
    files: [one.properties, nested/two.properties]
  ios:
    files: three.properties
''');

      expect(project.run(const <String>[]).exitCode, 0);
      expect(project.read('one.properties'), '${_header}a=b\n');
      expect(project.read('nested/two.properties'), '${_header}a=b\n');
      expect(project.read('three.properties'), '${_header}c=d\n');
    });
  });

  group('flatten and separator', () {
    const nested = '''
  android:
    app:
      name: Demo
      id: com.example
''';

    test('nested keys are joined with `_` by default', () {
      expect(_render(nested), 'app_name=Demo\napp_id=com.example\n');
    });

    test('separator changes the joint', () {
      expect(_render(nested, output: '    separator: "-"'), 'app-name=Demo\napp-id=com.example\n');
    });

    test('flatten: false writes top-level keys as they are', () {
      expect(_render('  android:\n    a_b: c\n', output: '    flatten: false'), 'a_b=c\n');
    });

    test('flatten: false writes a list as comma-joined text', () {
      expect(_render('  android:\n    tags: [a, b]\n', output: '    flatten: false'), 'tags=a,b\n');
    });

    test('flatten: false rejects a nested mapping', () {
      final project =
          TestProject.create()..writeManifest('''
config:
$nested
outputs:
  android:
    files: [out.properties]
    flatten: false
''');

      final result = project.run(const <String>[]);

      expect(result.exitCode, 1);
      expect(result.err, contains('[outputs.android] `app` is a mapping'));
      expect(result.err, contains('set `flatten: true`'));
    });

    test('two keys that become the same key fail, naming both', () {
      final project =
          TestProject.create()..writeManifest('''
config:
  android:
    app:
      name: Nested
    app_name: Flat
outputs:
  android:
    files: [out.properties]
''');

      final result = project.run(const <String>[]);

      expect(result.exitCode, 1);
      expect(result.err, contains('config keys `app.name` and `app_name` both become `app_name`'));
      expect(project.exists('out.properties'), isFalse);
    });
  });

  group('values', () {
    test('scalars are written as text', () {
      expect(
        _render('''
  android:
    text: Demo
    int: 42
    double: 1.5
    bool: true
'''),
        'text=Demo\nint=42\ndouble=1.5\nbool=true\n',
      );
    });

    test('null becomes empty and a list becomes comma-joined text', () {
      expect(_render('  android:\n    none: null\n    list: [a, 1, null]\n'), 'none=\nlist=a,1,\n');
    });
  });

  group('escaping', () {
    test('a dot in a key becomes `__`', () {
      expect(_render('  android:\n    "a.b": c\n'), 'a__b=c\n');
    });

    test('a dot that collides with `__` fails', () {
      final project =
          TestProject.create()..writeManifest('''
config:
  android:
    "a.b": dotted
    a__b: underscored
outputs:
  android:
    files: [out.properties]
''');

      final result = project.run(const <String>[]);

      expect(result.exitCode, 1);
      expect(result.err, contains('both become `a__b`'));
    });

    test('backslashes are doubled', () {
      expect(
        _render(r'  android: {path: "C:\\temp"}'),
        r'path=C:\\temp'
        '\n',
      );
    });

    test('line breaks, tabs and form feeds are escaped', () {
      expect(
        _render(r'  android: {v: "a\nb\rc\td\fe"}'),
        r'v=a\nb\rc\td\fe'
        '\n',
      );
    });

    test('a leading space in a value is escaped, inner spaces are not', () {
      expect(
        _render('  android: {v: " a b"}'),
        r'v=\ a b'
        '\n',
      );
    });

    test('spaces, `=` and `:` in a key are escaped, but not in a value', () {
      expect(
        _render('  android: {"a b=c:d": "e=f:g"}'),
        r'a\ b\=c\:d=e=f:g'
        '\n',
      );
    });

    test('a comment marker is escaped only at the start', () {
      expect(
        _render('  android: {hash: "#1 a#b", bang: "!1 a!b"}'),
        r'hash=\#1 a#b'
        '\n'
        r'bang=\!1 a!b'
        '\n',
      );
    });
  });
}
