// dart format off
// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.
// ignore_for_file: type=lint

/// `--dart-define=ENV=<dev|staging|production>`
enum EnvDefine {
  dev('dev'),
  staging('staging'),
  production('production');

  const EnvDefine(this.value);

  /// The value as spelled in the manifest.
  final String value;

  /// Raw `ENV` the running app was compiled with.
  static const String rawValue = String.fromEnvironment('ENV', defaultValue: 'dev');

  /// [rawValue] resolved to a value, `null` when it matches none.
  ///
  /// Const, so branches on it are resolved at compile time and the
  /// unreachable ones are tree-shaken away.
  static const EnvDefine? maybeCurrent =
      rawValue == 'dev' ? dev :
      rawValue == 'staging' ? staging :
      rawValue == 'production' ? production :
      null;

  /// How the app was launched.
  ///
  /// Throws when `ENV` holds an undeclared value.
  static EnvDefine get current =>
      maybeCurrent ?? (throw StateError('ENV=$rawValue is not one of dev, staging, production'));

  /// [value] resolved to a value, `null` when it matches none.
  ///
  /// Matches exactly, as `String.fromEnvironment` does.
  static EnvDefine? tryParse(String? value) {
    for (final candidate in values) {
      if (candidate.value == value) {
        return candidate;
      }
    }

    return null;
  }
}

/// `--dart-define=EDGE=<default|value|current|hashCode|1st|it's|$x|a\b>`
enum Edge {
  default$('default'),
  value$('value'),
  current$('current'),
  hashCode$('hashCode'),
  v1st('1st'),
  itS('it\'s'),
  x('\$x'),
  aB('a\\b');

  const Edge(this.value);

  /// The value as spelled in the manifest.
  final String value;

  /// Raw `EDGE` the running app was compiled with.
  static const String rawValue = String.fromEnvironment('EDGE');

  /// [rawValue] resolved to a value, `null` when it matches none.
  ///
  /// Const, so branches on it are resolved at compile time and the
  /// unreachable ones are tree-shaken away.
  static const Edge? maybeCurrent =
      rawValue == 'default' ? default$ :
      rawValue == 'value' ? value$ :
      rawValue == 'current' ? current$ :
      rawValue == 'hashCode' ? hashCode$ :
      rawValue == '1st' ? v1st :
      rawValue == 'it\'s' ? itS :
      rawValue == '\$x' ? x :
      rawValue == 'a\\b' ? aB :
      null;

  /// How the app was launched.
  ///
  /// Throws when `EDGE` holds an undeclared value.
  static Edge get current =>
      maybeCurrent ?? (throw StateError('EDGE=$rawValue is not one of default, value, current, hashCode, 1st, it\'s, \$x, a\\b'));

  /// [value] resolved to a value, `null` when it matches none.
  ///
  /// Matches exactly, as `String.fromEnvironment` does.
  static Edge? tryParse(String? value) {
    for (final candidate in values) {
      if (candidate.value == value) {
        return candidate;
      }
    }

    return null;
  }
}

/// Values resolved by livery.
///
/// Free-form defines are read at compile time; config values are baked in
/// as constants.
abstract final class Defines {
  /// `--dart-define=BUILD_TAG=...`
  static const String buildTag = String.fromEnvironment('BUILD_TAG');

  /// `--dart-define=CHANNEL=...`
  static const String channel = String.fromEnvironment('CHANNEL', defaultValue: 'beta');
}
