// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object LiveryConfig {
    enum class Env { DEV, STAGING, PRODUCTION }
    enum class Flavor { FREE, PAID }
    enum class StoreChannel { APP_STORE, PLAY_STORE, _1ST }
    enum class Unused {}

    val ENV: Env = Env.DEV
    val FLAVOR: Flavor? = null
    val STORE_CHANNEL: StoreChannel = StoreChannel.PLAY_STORE
    val BUILD_TAG: String? = null
    val CHANNEL: String = "beta"
    val SIGNING: String = "debug"
    val UNUSED: Unused? = null

    const val APP_NAME: String = "Demo App"
    const val VERSION_CODE: Int = 42
    const val APP_ID: String = "com.example.demo"
    const val APP_ID_SUFFIX: String = ".dev"
    const val MINIFY: Boolean = false
    const val API_URL: String = "https://api.example.com/v1?lang=en&debug=1"
    const val API_TIMEOUT: Int = 30
    const val API_RATIO: Double = 1.5
    const val API_RETRY_FACTOR: Double = 2.0
    const val MIN_BALANCE: Int = -5
    const val INT_MAX: Int = 2147483647
    const val INT_MIN: Int = -2147483648
    const val BIG_DOUBLE: Double = 1e+21
    const val TINY_DOUBLE: Double = -1.5e-7
    const val _2FA_ENABLED: Boolean = true
    const val DOTTED_KEY: String = "dotted"
    const val TRICKY: String = "it's \$HOME \\ \"quoted\"\n\r\ttabbed\u0001\u007f\u0085 é"
}
