// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object Defines {
    enum class Env { DEV, STAGING, PRODUCTION }
    enum class Flavor { FREE, PAID }
    enum class StoreChannel { APP_STORE, PLAY_STORE, _1ST }
    enum class Unused {}

    val ENV: Env = Env.PRODUCTION
    val FLAVOR: Flavor? = Flavor.PAID
    val STORE_CHANNEL: StoreChannel = StoreChannel.PLAY_STORE
    val BUILD_TAG: String? = "nightly"
    val CHANNEL: String = "beta"
    val SIGNING: String = "release"
    val UNUSED: Unused? = null
}
