// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object LiveryConfig {
    enum class Env { DEV, STAGING, PRODUCTION }

    val ENV: Env = Env.STAGING
    val BUILD_TAG: String? = "rc1"

    const val APP_NAME: String = "Livery Staging"
    const val APP_ID: String = "dev.livery.example"
    const val APP_ID_SUFFIX: String = ".staging"
    const val VERSION_CODE: Int = 3
    const val MINIFY: Boolean = false
}
