import '../yaml_reader.dart';

/// Kind of a config value, as it came out of YAML.
///
/// A config entry is a leaf, so it is never a [map]; mappings only take part
/// in the checks that keep a key's kind the same everywhere.
enum ValueKind {
  string('a string'),
  int('an int'),
  double('a double'),
  bool('a bool'),
  none('null'),
  list('a list'),
  map('a mapping');

  const ValueKind(this.described);

  /// The kind as an error message names it.
  final String described;
}

/// The kind of [value], one of the values a [YamlTree] holds.
ValueKind valueKindOf(Object? value) => switch (value) {
  null => ValueKind.none,
  String() => ValueKind.string,
  int() => ValueKind.int,
  double() => ValueKind.double,
  bool() => ValueKind.bool,
  List<Object?>() => ValueKind.list,
  YamlTree() => ValueKind.map,
  _ => throw StateError('YAML produced an unexpected ${value.runtimeType}'),
};

/// [path] as a dotted key path, quoting a segment that holds a dot itself.
String dottedPath(List<String> path) => path.map((segment) => segment.contains('.') ? '"$segment"' : segment).join('.');

/// One leaf of the config an output merges, with its full key path.
///
/// `android: {app: {name: Demo}}` yields the entry `[android, app, name]`.
class ConfigEntry {
  const ConfigEntry({required this.path, required this.kind, required this.value});

  /// Key path segments from the merged sections down to the leaf.
  final List<String> path;
  final ValueKind kind;

  /// A [String], [int], [double], [bool], `null`, or a [List] of such values.
  final Object? value;
}

/// A define declared in the manifest, with the value this generation resolved
/// for it, or `null` when it has none.
class ResolvedDefine {
  const ResolvedDefine({required this.name, required this.value});

  final String name;
  final String? value;
}

/// Everything a format needs to render one output.
class RenderInput<O> {
  const RenderInput({
    required this.entries,
    required this.defines,
    required this.includeDefines,
    required this.options,
  });

  /// The merged sections, flattened to leaves in declaration order.
  final List<ConfigEntry> entries;

  /// Every declared define, in declaration order.
  final List<ResolvedDefine> defines;

  /// Whether the output includes the defines, the output's `include_defines`.
  final bool includeDefines;

  /// The output's options, as parsed by its format.
  final O options;
}

/// One output format: its id, the output options it accepts, its defaults and
/// its renderer.
///
/// This is the only place format-specific behaviour lives. Adding a format
/// means writing one of these and registering it in `formats.dart`; nothing
/// else branches on a format id.
abstract base class OutputFormat<O> {
  const OutputFormat();

  /// The value of an output's `format` key.
  String get id;

  /// Output keys this format accepts beyond the ones every output has.
  Set<String> get optionKeys;

  /// Sections an output merges when it does not say.
  List<String> defaultMerge(String outputName);

  /// Whether an output includes the defines when it does not say.
  bool get includesDefinesByDefault;

  /// Reads this format's options from the output's mapping.
  O parseOptions(YamlReader output);

  /// The full text of one generated file.
  ///
  /// Throws a `LiveryException` when the input cannot be rendered.
  String render(RenderInput<O> input);

  /// Parses the options of [output] and pairs them with this format.
  BoundFormat<O> bind(YamlReader output) => BoundFormat<O>._(this, parseOptions(output));
}

/// A format together with one output's parsed options.
class BoundFormat<O> {
  const BoundFormat._(this.format, this.options);

  final OutputFormat<O> format;
  final O options;

  String render({
    required List<ConfigEntry> entries,
    required List<ResolvedDefine> defines,
    required bool includeDefines,
  }) => format.render(
    RenderInput<O>(entries: entries, defines: defines, includeDefines: includeDefines, options: options),
  );
}

/// The "generated, do not edit" header for a format whose comments start with
/// [commentPrefix], followed by a blank line.
String generatedHeader(String commentPrefix) =>
    '$commentPrefix GENERATED BY livery. Do not edit by hand.\n'
    '$commentPrefix Regenerate with `dart run livery`.\n'
    '\n';
