// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object LiveryConfig {
    enum class App { DEMO, KIOSK }
    enum class Env { DEV, STAGING, PRODUCTION }

    val APP: App = App.KIOSK
    val ENV: Env = Env.PRODUCTION
    val BUILD_TAG: String? = null

    const val APP_NAME: String = "Kiosk"
    const val APP_ID: String = "dev.livery.kiosk"
    const val APP_ID_SUFFIX: String = ""
    const val VERSION_CODE: Int = 7
    const val MINIFY: Boolean = true
}
