// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object LiveryConfig {
    enum class Env { DEV, STAGING, PRODUCTION }

    val ENV: Env = Env.PRODUCTION
    val BUILD_TAG: String? = null

    const val APP_NAME: String = "Livery"
    const val APP_ID: String = "dev.livery.example"
    const val APP_ID_SUFFIX: String = ""
    const val VERSION_CODE: Int = 3
    const val MINIFY: Boolean = true
}
