// GENERATED BY livery. Do not edit by hand.
// Regenerate with `dart run livery`.

object LiveryConfig {
    enum class App { DEMO, KIOSK }
    enum class Env { DEV, STAGING, PRODUCTION }

    val APP: App = App.DEMO
    val ENV: Env = Env.DEV
    val BUILD_TAG: String? = null

    const val APP_NAME: String = "Demo Dev"
    const val APP_ID: String = "dev.livery.demo"
    const val APP_ID_SUFFIX: String = ".dev"
    const val VERSION_CODE: Int = 12
    const val MINIFY: Boolean = false
}
